export const LOGIN_CREATER = "LOGIN_CREATER"
export const LOGIN_MEMBER = "LOGIN_MEMBER"
export const NAME_REGISTER_CHANGE = "NAME_REGISTER_CHANGE"
export const NUMBER_REGISTER_CHANGE = "NUMBER_REGISTER_CHANGE"
export const EMAIL_REGISTER_CHANGE = "EMAIL_REGISTER_CHANGE"
export const PASSWORD_REGISTER_CHANGE = "PASSWORD_REGISTER_CHANGE"


